version: 2
jobs:
  test-3.6: &full-test-template
    docker:
      - image: circleci/python:3.6-jessie

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: install cmake 3.11
          command: |
            #sudo apt-get install software-properties-common --force-yes
            #sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x --force-yes
            #sudo apt-get update --force-yes && sudo apt-get install cmake --force-yes
            
            sudo apt-get install build-essential
            #wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
            wget http://www.cmake.org/files/v3.11/cmake-3.11.4.tar.gz
            tar xf cmake-3.11.4.tar.gz
            cd cmake-3.11.4
            ./configure
            make
            sudo make install
            #sudo apt-get update --force-yes
            #sudo apt-get install software-properties-common --force-yes
            #sudo apt-get update --force-yes
            #sudo add-apt-repository --yes ppa:george-edison55/cmake-3.2
            #sudo apt-get install cmake --force-yes
            
            cmake --version
      
      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: create virtualenv
          command: |
            python -m virtualenv env
      
      - run: &install-dependencies-template
          name: install dependencies
          command: |
            . env/bin/activate 
            python --version
            pip install -r requirements.txt
  
      - run: &install-package-template
          name: install package
          command: |
            . env/bin/activate
            python setup.py install
      
      - run: &run-tests-template
          name: run unittests
          command: |
            . env/bin/activate
            python --version
            coverage run -m unittest discover
   
workflows:
  version: 2
  test:
    jobs:
      - test-3.6