version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:

  test-linux-36: &linux-test-template
    docker:
      - image: colon0722/manylinux_cmake:latest
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.6.5
      
    working_directory: ~/repo

    steps:

      - checkout
      
      - run: &install-python-template
          name: install python from pyenv
          command: |
            #echo 'export PATH=$PYENV_ROOT/bin:$PATH' >> $BASH_ENV
            #source $BASH_ENV
            #git clone https://github.com/pyenv/pyenv.git $PYENV_ROOT
            #eval "$(pyenv init -)" 
            #pyenv install $PYTHON -s
            echo 'export PATH=/opt/python/cp36-cp36m/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV
            python -V
      
      
      - run: &create-virtualenv-template
          name: create virtualenv
          command: |
            python --version
            python -m pip install virtualenv
            python -m virtualenv env
      
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: &install-dependencies-template
          name: install dependencies
          command: |
            . env/bin/activate 
            python --version
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./env
          key: v2-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
  
      - run: &install-package-template
          name: install package
          command: |
            . env/bin/activate
            python --version
            python setup.py install

      - run: &run-tests-template
          name: run unittests
          command: |
            . env/bin/activate
            python --version
            coverage run -m unittest discover
  
  
  test-linux-python35:
    <<: *linux-test-template
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.5.5
  
  test-linux-python37:
    <<: *linux-test-template
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.7.5
  
  test-linux-python38:
    <<: *linux-test-template
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.8.0
  
  deploy-linux:
    docker:
      - image: colon0722/manylinux_cmake:latest
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.6.5
      
    working_directory: ~/repo

    steps:

      - checkout

      - run: *install-python-template
      
      - run:
          name: build wheels
          command: |
            for PYBIN in /opt/python/*/bin; do
              echo $PYBIN
              if "${PYBIN}/python" -c "import sys; sys.exit(sys.version_info>=(3, 6) and sys.version_info<(3, 7))"; then continue; fi;
              "${PYBIN}/pip" install -r requirements.txt
              "${PYBIN}/pip" wheel . -w ./wheelhouse
              "${PYBIN}/python" setup.py sdist -d ./dist
            done
      
      - run:
          name: bundle shared libraries into wheels
          command: |
            ls ./wheelhouse/
            for whl in ./wheelhouse/pyqubo*.whl; do
              auditwheel repair "$whl" -w ./dist
            done

      
      - store_artifacts:
          path: ./dist

      - run: &init_pypirc
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            # for testpypi
            echo -e "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
            echo -e "password = $TEST_PYPI_PASSWORD" >> ~/.pypirc

            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            #echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: python setup
          command: |
            echo 'export PATH=/opt/python/cp36-cp36m/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV
            python -V
      
      - run: *create-virtualenv-template
      
      - run:
          name: install twine and deploy
          command: |
            . env/bin/activate
            pip install twine
            twine upload --skip-existing ./dist/*
  
  test-osx:
    macos:
      xcode: "11.2.1"
    environment:
      PYTHON: 3.6.5
      HOMEBREW_NO_AUTO_UPDATE: 1
    
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: check brew
          command: |
            brew --version
            brew install cmake

      - run:
          name: install pyenv
          command: |
            brew install pyenv

      - restore_cache:
          keys:
            - pyenv-{{ .Environment.CIRCLE_JOB }}-xcode11.2.1

      - run:
          name: install python
          command: |
            pyenv install $PYTHON -s

      - save_cache:
          paths:
            - ~/.pyenv
          key: pyenv-{{ .Environment.CIRCLE_JOB }}-xcode11.2.1
      
      - run:
          name: create virtualenv
          command: |
            eval "$(pyenv init -)"
            pyenv local $PYTHON
            python -m pip install virtualenv
            python -m virtualenv env
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-dependencies-template

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-package-template

      - run: *run-tests-template


  build-win:
    executor:
      name: win/default
    
    environment:
      PYTHON: 3.6.5
      PYTHON_PATH: C:/Python36/

    steps:
      - checkout

      - run:
          command: |
            choco install -y cmake
            choco install -y python --version "${PYTHON}"
          shell: bash.exe
      
      - run:
          command: |
            export PATH=$PATH:"C:\Program Files\CMake\bin"
            $PYTHON_PATH/python -m pip install -r requirements.txt
            #python setup.py install
            
          shell: bash.exe
  
  deploy-win:
    executor:
      name: win/default
      shell: bash.exe
    
    environment:
      PYTHON: 3.6.5
      PYTHON_PATH: C:/Python36/

    steps:
      - checkout

      - run:
          name: install cmake and python
          command: |
            choco install -y cmake
            choco install -y python --version "${PYTHON}"
          shell: bash.exe
      
      - run:
          name: create wheel
          command: |
            export PATH=$PATH:"C:\Program Files\CMake\bin"
            $PYTHON_PATH/python -m pip install -r requirements.txt
            $PYTHON_PATH/python -m pip install wheel twine
            $PYTHON_PATH/python setup.py bdist_wheel
            $PYTHON_PATH/python -m pip install pyqubo --no-index -f dist
      
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            # for testpypi
            echo -e "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
            echo -e "password = $TEST_PYPI_PASSWORD" >> ~/.pypirc

            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            #echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            echo %PYPI_USERNAME%
          shell: bash.exe

      - run:
          name: upload wheel
          command: |
            $PYTHON_PATH/python -m twine upload ./dist/*
          shell: bash.exe
  
  deploy-win2:
    executor:
      name: win/default
      shell: bash.exe

    steps:
      - checkout

      - run:
          name: echo MY_VAR
          command: |
            echo ${MY_VAR}
          shell: bash.exe

  test-linux-env:
    docker:
      - image: colon0722/manylinux_cmake:latest
    environment:
      PYENV_ROOT: tmp/.pyenv
      PYTHON: 3.6.5
      
    working_directory: ~/repo

    steps:

      - checkout
      
      - run:
          name: echo MY_VAR
          command: |
            echo ${MY_VAR}


workflows:
  version: 2
  build-test:
    jobs:
      #- test-osx-3.6
      #- deploy-linux
      #- test-linux-36
      #- deploy-win2
      - test-linux-env