name: build-test

on: 
  workflow_dispatch:

env:
  python-version: 3.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ env.python-version }}
    - name: Set up Python ${{ env.python-version }} cache 
      run: which python > ~/.python3_path.txt
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('~/.python3_path.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Install dependencies 
      run: |
        pip install --upgrade pip wheel setuptools build cmake ninja
    - name: Test 
      run: |
        python setup.py build --debug test
    - name: Install 
      run: |
        python setup.py install
    - name: Install 
      run: |
        python setup.py install[dimod-old-version]
    - name: IMPORT
      run: |
          python -c 'import pprint; import pyqubo; pprint.pprint(dir(pyqubo), compact=True)'
    - name: IMPORT
      run: |
          python -c 'import pprint; import cpp_pyqubo; pprint.pprint(dir(cpp_pyqubo), compact=True)'
